name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29b9d74b52b1f8301de97632535718b8c905633bcc86b5e88799e5a6c3da2e16"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
