name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9ffc50dd28ed947124f13a8b432a968dfa64790e086cb994aaea4f48d452368"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
