name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0688de86495ae4b0b3c282517d3d502a2d8e11874e408481b564f73ed6cae142"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
