name = "Wold's Vaults"
author = "iwolfking"
version = "0.18.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb0038a2358452c76704049de57360de36f0d1a75a094fa8da5a98e4cc4cfd2a"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
