name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0972760d2445931f44cac6139f667e096b14f711bf0a4c3b22d8f9e94c4021c4"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
