name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e863200e3ce5fed2ccee160adcb9061b259f933bf5b8ca68e64e2e939df4156"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
