name = "Wold's Vaults"
author = "iwolfking"
version = "0.19.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3761bde22e47ef2e4d1084e7400d3d04db72747cd9634607799aac9f8879ec4a"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
