name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df789347f9e099ca40a4b9b22a7c0676ea67812f2aff270dc49b83db7b83fc0"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
