name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b3b76ff6430666c2cfce14233d02ea240bd862202f8789ee59dd40fa63d03d2"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
